### ISSUE TITLE
翻译任务认领说明

### ISSUE THREAD

**Issue by QC-L** [slidevjs/docs-cn#8]
# 翻译任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
>
> 2. 认领开始前，请务必阅读 [翻译流程说明](https://github.com/slidevjs/docs-cn/issues/9)

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] install

领取过：

* [ ] install (@QC-L)

领取过，已完成：

* [x] install (@QC-L) #10

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @QC-L | 2021.05.18 - 2021.05.20
```

示例效果：

Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @QC-L | 2021.05.18 - 2021.05.20

当完成时，请修改自己的认领评论，添加 PR 信息：

Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  install | @QC-L | 2021.05.18 - 2021.05.20 | #10

## 任务认领列表

Todo List:

- [x] [guide](https://github.com/slidevjs/docs-cn/tree/main/guide/)
  - [x] [syntax](https://github.com/slidevjs/docs-cn/tree/main/guide/syntax.md) (@QC-L) #12 
  - [x] [animations](https://github.com/slidevjs/docs-cn/tree/main/guide/animations.md) (@Ivocin) #39 
  - [x] [editors](https://github.com/slidevjs/docs-cn/tree/main/guide/editors.md) (@jacob-lcs ) #38 
  - [x] [exporting](https://github.com/slidevjs/docs-cn/tree/main/guide/exporting.md) (@QC-L) #21 
  - [x] [index](https://github.com/slidevjs/docs-cn/tree/main/guide/index.md) (@Ivocin) #4
  - [x] [install](https://github.com/slidevjs/docs-cn/tree/main/guide/install.md) (@QC-L) #10
  - [x] [navigation](https://github.com/slidevjs/docs-cn/tree/main/guide/navigation.md) (@ChuanfengZhang) #23 
  - [x] [presenter-mode](https://github.com/slidevjs/docs-cn/tree/main/guide/presenter-mode.md) (@KimYangOfCat) #37 
  - [x] [recording](https://github.com/slidevjs/docs-cn/tree/main/guide/recording.md) (@QC-L) #22 
  - [x] [why](https://github.com/slidevjs/docs-cn/tree/main/guide/why.md) (@Notobey) #15 
- [x] [custom](https://github.com/slidevjs/docs-cn/tree/main/custom/)
  - [x] [index](https://github.com/slidevjs/docs-cn/tree/main/custom/index.md) (@ArcherGu) #13 
  - [x] [config-katex](https://github.com/slidevjs/docs-cn/tree/main/custom/config-katex.md) (@ArcherGu) #26 
  - [x] [config-mermaid](https://github.com/slidevjs/docs-cn/tree/main/custom/config-mermaid.md) (@ArcherGu) #27 
  - [x] [config-monaco](https://github.com/slidevjs/docs-cn/tree/main/custom/config-monaco.md) (@zrr1999) #28 
  - [x] [config-vite](https://github.com/slidevjs/docs-cn/tree/main/custom/config-vite.md) (@QC-L) #30 
  - [x] [config-windicss](https://github.com/slidevjs/docs-cn/tree/main/custom/config-windicss.md) (@QC-L) #31 
  - [x] [directory-structure](https://github.com/slidevjs/docs-cn/tree/main/custom/directory-structure.md) (@QC-L) #32 
  - [x] [highlighters](https://github.com/slidevjs/docs-cn/tree/main/custom/highlighters.md) (@songhn233) #25 
- [x] [builtin](https://github.com/slidevjs/docs-cn/tree/main/builtin)
  - [x] [components](https://github.com/slidevjs/docs-cn/tree/main/builtin/components.md) (@KnowsCount) #11 
  - [x] [layouts](https://github.com/slidevjs/docs-cn/tree/main/builtin/layouts.md) (@ChuanfengZhang)  #24 
- [x] [themes](https://github.com/slidevjs/docs-cn/tree/main/themes)
  - [x] [gallery](https://github.com/slidevjs/docs-cn/tree/main/themes/gallery.md) (@QC-L) #33 
  - [x] [use](https://github.com/slidevjs/docs-cn/tree/main/themes/use.md) (@Megrax) #35 
  - [x] [write-a-theme](https://github.com/slidevjs/docs-cn/tree/main/themes/write-a-theme.md) (@songhn233) #18 
- [x] [resources](https://github.com/slidevjs/docs-cn/tree/main/resources)
  - [x] [covers](https://github.com/slidevjs/docs-cn/tree/main/resources/covers.md) (@raintygao) #34

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @QC-L | 2021.05.18 - 2020.05.20

**Comment by Notobey** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  why | @Notobey | 2021.05.15 - 2020.05.20

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  syntax | @QC-L | 2021.05.18 - 2020.05.20

**Comment by KnowsCount** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @QC-L | 2021.05.15 - 2021.05.28

**Comment by ArcherGu** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
custom |  index | @ArcherGu | 2021.05.15 - 2020.05.20

**Comment by Megrax** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
themes |  use | @Megrax | 2021.05.16 - 2020.05.23

**Comment by Ivocin** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  animations | @Ivocin  | 2021.05.17 - 2020.05.20 | -

**Comment by songhn233** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
themes |  write-a-theme | @songhn233 | 2021.05.17 - 2020.05.20

**Comment by jacob-lcs** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide | editors | @jacob-lcs | 2021.05.17 - 2020.05.20

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  presenter-mode | @KimYangOfCat | 2021.05.17 - 2020.05.20

**Comment by ChuanfengZhang** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  navigation | @ChuanfengZhang | 2021.05.17 - 2021.05.18

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  exporting | @QC-L | 2021.05.18 - 2021.05.20

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  recording | @QC-L | 2021.05.18 - 2021.05.20 | -

**Comment by ChuanfengZhang** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
builtin |  layouts | @ChuanfengZhang  | 2021.05.17 - 2021.05.18

**Comment by songhn233** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
custom |  highlighters | @songhn233 | 2021.05.17 - 2021.05.20

**Comment by ArcherGu** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
custom |  config-katex | @ArcherGu  | 2021.05.17 - 2021.05.20

**Comment by ArcherGu** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
custom |  config-mermaid | @ArcherGu  | 2021.05.17 - 2021.05.20 | -

**Comment by zrr1999** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
guide |  install | @zrr1999 | 2021.05.18 - 2021.05.22

**Comment by raintygao** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
resource |  covers | @raintygao | 2021.05.18 - 2021.05.19

**Comment by Ivocin** [comment]
从 5 月 13 日建立本仓库到 5 月 18 日完成全部文档翻译，仅用 6 天时间就完成了全部文档的翻译工作，感谢小伙伴们的辛苦付出
